# Generated by Django 4.2.6 on 2023-10-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="new_user",
            new_name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
